### PR TITLE
ENH : structs for handling MDS data structures

### PR DESCRIPTION
**Pull request by tacaswell**
Added machinery to generate namedtuple sub-classes for
managing data structures to/from MDS

### CODE REVIEW

**Comment by danielballan** [comment]
Is this superceded?

**Comment by tacaswell** [comment]
Mostly maybe. We might still want a version of this to fully insulate from
mongo.

**Comment by danielballan** [comment]
I now realize that I have been starting to build what you have already built in this PR. I'd like to merge it.

**Comment by danielballan** [comment]
This doesn't break anything. I'm going for it! :- D

**Pull request merged**
