### PR TITLE
ENH: Added auto-generated changelog

### PR DESCRIPTION
**Pull request by ericdill**
- changelog generated by github_changelog_generator

@danielballan I remember you saying something about a changelog and I just stumbled across [this repo](https://github.com/skywinder/github-changelog-generator) this morning.  It generated the changelog in this PR. Thoughts @tacaswell @danielballan ?

### CODE REVIEW

**Comment by ericdill** [comment]
Using skywinder/github_changelog_generator:

```
git clone https://github.com/skywinder/github_changelog_generator
cd github_changelog_generator
gem build github_changelog_generator.gemspec 
sudo gem install github_changelog_generator-1.3.10.gem 
github_changelog_generator -u NSLS-II -p dataportal -t {your_gh_api_token}
```

**Comment by danielballan** [comment]
1. We must have a change (a.k.a. release notes) for our next deployment and all future deployments.
2. I am skeptical that an auto-generated dump can do this well. To give you an idea of what I have in mind, I think the golden standard for useful release notes is [pandas' what's new](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html).
3. But maybe I'm being crotchety and some automated assistance would be useful. I'm open to it.

**Comment by tacaswell** [comment]
I am also skeptically of auto-generated change logs, the signal gets lost in the noise.

**Comment by danielballan** [comment]
You could use that auto-generated dump as a starting point. It should be condensed (many issues and PRs go into one bullet point), reworded for a general audience, and in some cases fleshed out with brief examples.

**Comment by ericdill** [comment]
@danielballan @tacaswell You both make compelling points. I guess I was thinking that this autogenerated log was better than nothing and it comes at almost zero cost.  @danielballan Using this autogenerated log as a starting point for something like the 'whatsnew' in pandas does indeed seem like a much better idea than using the raw autogenerated logs. Let me note that I'm not trying to advocate for "WE MUST USE THIS AUTOGENERATION TOOL" or any nonsense along those lines as I really don't have any strong feels on the matter of using `github_changelog_generator` or not. If it's useful, great!  If not, I've now spent longer writing this comment than I did figuring out how to use this autogeneration tool in the first place :grinning:

**Comment by ericdill** [comment]
Oh, one possible snafu in using this autogeneration tool is that it only generates markdown.  For the release notes was the plan to use rest?

**Comment by tacaswell** [comment]
pandoc can take care of md -> rst conversion

**Pull request closed without merging**
