### PR TITLE
ENH: Switching data sets now resets plot buttons

### LINKED ISSUE #39: ToggleButtons on the Scalar plot controls are not updating when data sets are switched
Reported by @tacaswell

### PR DESCRIPTION
**Pull request by ericdill**
- Closes #39

### CODE REVIEW

**Comment by ericdill** [comment]
Let me rebase this onto new master and make sure travis passes

**Comment by tacaswell** [comment]
Is this code covered by the tests?

**Comment by ericdill** [comment]
None of replay is covered by tests.

**Comment by ericdill** [comment]
So this could actually be merged now then

**Pull request merged**
