### PR TITLE
ENH/TST: Add replay History object, maintaining state in a sqlite file.

### PR DESCRIPTION
**Pull request by danielballan**
This is based on a conversation with @ericdill and @tacaswell yesterday. It implements a class that loads and saves arbitrary dictionaries, intended to hold replay configuration state like `plot_x` and `plot_y`, in a sqlite file. The entire history of a given entry is maintained in the file.

### CODE REVIEW

**Comment by tacaswell** [comment]
There is an extra commit on my branch from eric correcting spelling that should be pulled over.

**Comment by danielballan** [comment]
Added.

**Comment by ericdill** [comment]
To avoid this turning in to a massive PR with my replay updates sitting on top of these commits, I vote for merging this now and then i can put in a PR that uses this

**Comment by tacaswell** [comment]
I am happy with this.  Given the development history I think @ericdill needs to push the green button.

**Pull request merged**
