### PR TITLE
ENH: Use new metadatastore recursive printing

### PR DESCRIPTION
**Pull request by ericdill**
Changes:
- Use the `Document` class to perform the `__str__` functionality 
- Rename the existing `__str__` in the `Header` class to `summary` 
- Make `summary` a property

### CODE REVIEW

**Comment by tacaswell** [comment]
needs #171 to be merged before this will pass.

**Comment by danielballan** [comment]
@ericdill Would you paste some demo output here? Makes it easy to update the docs later.

**Comment by ericdill** [comment]
Recursively print the Document class and format the DataKeys of an EventDescriptor into a table. 

## Example header output

``` python
from dataportal import DataBroker as db
print(db[-1])
```

produces

```
Header
------
beamline_id    : csx                                     
group          :                                         
moon           : full                                    
owner          :                                         
plotx          : linear_motor                            
ploty          : [u'total_img_sum']                      
project        :                                         
run_start_id   : 5538f65f3892c9066bf8917a                
run_start_uid  : 5a84b162-126b-449b-b00a-c2b506c9619e    
sample         : {}                                      
scan_id        : 36                                      
start_datetime : 2015-04-23 09:40:47.857965              
start_time     : 1429796447.86                           

  BeamlineConfig
  ==============
  config_params  : {u'my_beamline': u'my_value'}           
  id             : 5538f65f3892c9066bf89179                
  time           : 1429796447.84                           
  time_as_datetim: 2015-04-23 09:40:47.835954              
  uid            : 8990e097-000c-4592-841d-3dcdfc04bb88    

  EventDescriptor
  ===============
  +---------------+--------+------------+----------+-------------+
  | key name      | dtype  |   shape    | external |    source   |
  +---------------+--------+------------+----------+-------------+
  | img           | array  | FILESTORE: |  [5, 5]  |     CCD     |
  | img_sum_x     | array  | FILESTORE: |   [5]    |   CCD:xsum  |
  | img_sum_y     | array  | FILESTORE: |   [5]    |   CCD:ysum  |
  | img_x_max     | number |    None    |    []    |   CCD:xmax  |
  | img_y_max     | number |    None    |    []    |   CCD:ymax  |
  | linear_motor  | number |    None    |    []    | PV:ES:sam_x |
  | total_img_sum | number |    None    |    []    |   CCD:sum   |
  +---------------+--------+------------+----------+-------------+
  id             : 5538f65f3892c9066bf8917b                
  time           : 0.0                                     
  time_as_datetim: 1969-12-31 19:00:00                     
  uid            : 5f6559a2-f643-4ce8-9615-43538ddf0e71    


  EventDescriptor
  ===============
  +----------+--------+-------+----------+------------+
  | key name | dtype  | shape | external |   source   |
  +----------+--------+-------+----------+------------+
  | Tsam     | number |  None |    []    | PV:ES:Tsam |
  +----------+--------+-------+----------+------------+
  id             : 5538f65f3892c9066bf8917c                
  time           : 0.0                                     
  time_as_datetim: 1969-12-31 19:00:00                     
  uid            : 2aa492c6-072d-4de0-a5ea-8c87dffcdb4f    
```

**Comment by ericdill** [comment]
@danielballan should `hdr.summary` print or return a formatted string?

**Comment by danielballan** [comment]
Following pandas.DataFrame.describe(), I would say return a string. I am used to seeing it as a method (a la `describe()`) but I think I agree that `summary`, a property, is the best choice here.

Kick Travis now that the necessary MDS fix has been merged. If it passes, I say this is ready to merge.

**Comment by tacaswell** [comment]
I am a tad hesitate to use `describe` due to shadowing with the same in
ophyd, but it seems pandas got there first so probably not really a concern.

**Comment by danielballan** [comment]
We are using `summary` to avoid shadowing `describe`. I wish we could be consistent with pandas here, as this is a lot like _their_ `describe`, but staying clear of ophyd seems more important.

**Comment by ericdill** [comment]
Tests are passing, can someone click big green?

**Comment by ericdill** [comment]
Oh, wait, needs NSLS-II/metadatastore#137 first

**Pull request merged**
