### PR TITLE
WIP: Updating a DataMuxer

### PR DESCRIPTION
**Pull request by danielballan**
It works like this:

```
header = DataBroker[-1]  # for example
events = DataBroker.fetch_events(header)
dm = DataMuxer.from_events(events)

# more Events are added to MDS...

DataBroker.update(dm)
```

DataBroker is using only public attributes of `dm` to do its work. It's no problem if Events are added out of order. DataBroker dumps _all_ the Events it finds in the DataMuxer, and DataMuxer takes care of identifying duplicates.

I christened the method `DataBroker.update`. Or we could call it `DataBroker.refresh`. I like either one.

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1:  On doing it this way, seems to need a rebase.

**Comment by ericdill** [comment]
yeah i like this too, sorry for breaking it by merging #75

**Comment by tacaswell** [comment]
@danielballan Do you want this merged for deployment this week?  I can fix the conflicts locally.

**Comment by danielballan** [comment]
Provided this is what @dchabot has in mind.

**Comment by danielballan** [comment]
Rebased.

**Comment by danielballan** [comment]
DO NOT MERGE. @ericdill and I have developed a better way to do this, one that will be (1) immediately better-performing and (2) easily extensible to direct hooks into EPICS for people who want to update their view of the data as fast as possible by bypassing storage.

**Comment by danielballan** [comment]
Superceded by #91.

**Pull request closed without merging**
