### PR TITLE
API : change begin/end event names

### PR DESCRIPTION
**Pull request by tacaswell**
BeginRunEvent -> RunStart
EndRunEvent -> RunEnd

insert_end_run -> insert_run_end
insert_begin_run -> insert_run_start

sundry variable/arg name/doc changes

### CODE REVIEW

**Comment by tacaswell** [comment]
This will need to have travis kicked to re-start once the mds PR is merged.

**Comment by ericdill** [comment]
Did you do a search of the `.enaml` files too? or just the `.py`?

**Comment by tacaswell** [comment]
didn't touch the enaml files, but replay still seems to work...one sec

**Comment by tacaswell** [comment]
There are not any instances of the word 'begin' left in the repo so I think it is ok

**Pull request merged**
