### PR TITLE
Sb tweak

### PR DESCRIPTION
**Pull request by tacaswell**
This is dependent on https://github.com/NSLS-II/metadatastore/pull/106

### CODE REVIEW

**Comment by danielballan** [comment]
Why are Documents iterable?

**Comment by danielballan** [comment]
Nevermind. Documents are dicts. OK.

**Comment by tacaswell** [comment]
The tests are failing due to dependency on MDS PR.

@ericdill Can you take a look at the changes to the various `model.py`?

**Comment by ericdill** [comment]
as long as it works, fine by me

**Comment by ericdill** [comment]
Looks good to me

**Pull request merged**
