### PR TITLE
WIP: Move replay up to a top-level package

### PR DESCRIPTION
**Pull request by danielballan**
In this PR, replay would still be distributed with dataportal with their shared setup.py, but replay would be `replay`, not `dataportal.replay`. This makes it possible to import dataportal even if there are problems dealing with the fact that enaml must always be imported before matplotlib.

(Said problems have been resolved so far, but it will probably come up again. Yesterday, we saw how easy it is for users to sneakily import matplotlib somewhere where it takes us an hour to find it.)

### CODE REVIEW

**Comment by danielballan** [comment]
Note to selves: `run_tests.py` must also be updated to include replay before merging.

**Comment by ericdill** [comment]
I'm fairly certain that it does...  Doesn't replay still pop up when you
execute `python run_tests.py`?

**Comment by danielballan** [comment]
Nose is fine, but coverage isn't picking up replay.

**Comment by ericdill** [comment]
I think adding `source=replay` to the run section of .coveragerc will fix that

**Comment by danielballan** [comment]
@ericdill It looks like some imports are still broken here. Can you bail me out?

**Comment by tacaswell** [comment]
Closed as #164 is merged.

**Pull request closed without merging**
